name: Linting Continuous Integration

on:
  push:
    branches: [ main ]
    paths: 
      - Source/**
  pull_request:
    branches: [ main ]
    paths: 
      - Source/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install required dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Requirements.txt
    - name: Run Linters
      run: |
        cd Source/
        make pylint
        make pylama
        make pycodestyle
        make pydocstyle
        make pyflakes
    - name: Clean Cached Files
      run: |
        cd Source/
        make clean